spring:
    profiles:
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: selecao
server:
    port: 8080


application:
    urlProcessarAlertas: https://selecao-involves.agilepromoter.com/pesquisas